# Generated by Django 3.0.8 on 2020-07-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('merchant_order_id', models.CharField(max_length=20)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default='', max_length=25)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('cancel', 'cancel'), ('pending', 'pending')], max_length=8)),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unitary_price', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.Order')),
            ],
        ),
    ]
