export const FETCH_PRODUCTS = "FECTH_PRODUCTS";
export const FETCH_PROMOTIONS = "FECTH_PROMOTIONS";
export const FETCH_CATEGORIES = "FECTH_CATEGORIES";
export const SHOW_PRODUCT_DETAIL = "SHOW_PRODUCT_DETAIL";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_PRODUCT = "FILTER_BY_PRODUCT";
