# Generated by Django 3.0.8 on 2020-07-28 17:34

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('orden', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('logo', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='owner/%Y/%m/%d')),
                ('instagram', models.URLField()),
                ('whatsapp', models.URLField()),
                ('cbu', models.CharField(max_length=30)),
                ('alias_CBU', models.CharField(max_length=50)),
                ('cuil', models.CharField(max_length=11)),
                ('cuenta', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Description')),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('available_stock', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('new_enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='nutri.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('product', 'product'), ('category', 'category'), ('shipping', 'shipping'), ('all', 'all')], max_length=20)),
                ('_type', models.CharField(choices=[('percent', 'percent'), ('nxm', 'nxm'), ('free', 'free'), ('code', 'code')], max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='products/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nutri.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products', to='nutri.Promotion'),
        ),
    ]
