# Generated by Django 3.0.8 on 2020-09-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='target',
            field=models.CharField(choices=[('product', 'product'), ('category', 'category'), ('shipping', 'shipping'), ('payment', 'payment'), ('all', 'all')], max_length=20),
        ),
    ]
