# Generated by Django 3.0.8 on 2020-07-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
