# Generated by Django 3.0.8 on 2020-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_auto_20200712_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
