# Generated by Django 3.0.8 on 2020-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_auto_20200910_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
