# Generated by Django 3.1.6 on 2021-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0003_promotion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.ImageField(upload_to='owner/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
